In [4]:
import pandas as pd
df = pd.read_csv('output.csv')
df

,Timestamp,Open,High,Low,Close,Volume,Timestamp2
0,1706486400,21433.10,21763.20,21429.60,21737.6,0,2024-01-29 05:30:00+05:30
1,1706572800,21775.80,21813.10,21501.80,21522.1,0,2024-01-30 05:30:00+05:30
2,1706659200,21487.20,21741.30,21448.80,21725.7,0,2024-01-31 05:30:00+05:30
3,1706745600,21780.70,21832.90,21658.80,21697.4,0,2024-02-01 05:30:00+05:30
4,1706832000,21812.80,22126.80,21805.60,21853.8,0,2024-02-02 05:30:00+05:30
...,...,...,...,...,...,...,...
226,1735171200,23775.80,23854.50,23653.60,23750.2,0,2024-12-26 05:30:00+05:30
227,1735257600,23801.40,23938.85,23800.60,23813.4,0,2024-12-27 05:30:00+05:30
228,1735516800,23796.90,23915.35,23599.30,23644.9,0,2024-12-30 05:30:00+05:30
229,1735603200,23560.60,23689.85,23460.45,23644.8,0,2024-12-31 05:30:00+05:30
230,1735689600,23637.65,23822.80,23562.80,23742.9,0,2025-01-01 05:30:00+05:30

In [ ]:
import pandas_ta as ta
df['EMA'] = ta.ema(df.Close, length=10)

ImportError: cannot import name 'NaN' from 'numpy' (/Users/sunilbiswakarma/development/fyers/venv/lib/python3.11/site-packages/numpy/__init__.py)